### ISSUE TITLE
Review Deployment Setup

### ISSUE THREAD

**Issue by lgastler** [schule4-0/pets#4]
Hi together, 

I just connected the repo to Vercel for you to get a running deployment. 

Preview branches, etc. are all enabled, so for every PR from now on, you should get a preview environment automatically created, and the Vercel Bot should comment the URL, etc. into the PR. 

I set [pets.schule4-0.dev](pets.schule4-0.dev) as the domain for the `main` branch and [preview.pets.schule4-0.dev](preview.pets.schule4-0.dev) for the `develop` branch. Later, we can / will switch that to use the schule4-0.de TLD. 

If you need to adjust any settings on the Vercel side, f.e. Environment Variables Please let me know. 

If there are any other questions, feel free to send them here, by email, etc. 

Greetings from Italy
Lennart

**Comment by stapps21** [comment]
It works fine - thanks!
