### ISSUE TITLE
Implement Custom Color Palette in base.css

### ISSUE THREAD

**Issue by stapps21** [schule4-0/pets#5]
## Description

Currently, our project uses the standard Vue color palette. We propose creating a custom color palette and implementing it as variables within `base.css`.

## Action

- [ ] Create a color palette.
- [ ] Update `base.css` to use the new color palette.

**Comment by stapps21** [comment]
Based on that the "Schule 4.0" Website looks like they use Material 3 as a styleguide, I would suggest, that we design our Website in a similar way. (https://m3.material.io/)
- Create a Material 3 Theme (https://material-foundation.github.io/material-theme-builder/)
- Maybe we can also use the material-web library, it uses Material 3  (https://github.com/material-components/material-web/tree/main)

What's your opinion on that?

**Comment by pascall2** [comment]
It looks like https://www.schule4-0.de/blog/ps40-spuren-im-netz/ use a custom design. Of course, this is more work, but for a game this kind of design is maybe a better fit.
However, a Material 3 theme with "game" like colors could also work.

**Comment by stapps21** [comment]
Okay, so I think we can wait for a theme integration after we fully implemented the first minigame and then have a look on what core elements we really need. I think the theme is not required for the graphics so we can implement it afterwards.
Let's keep this open and adjust things later.

**Comment by stapps21** [comment]
Simple color theme was added here https://github.com/schule4-0/pets/pull/67/commits/aacfd65a59a1fb9ab7a9def662b775937a2014df
